#pragma once

#include "../common/envvars.h"

#define OSSLTRACE_AUDIT_ENV_VAR "OSSLTRACE_AUDIT_LIB_PATH"
#ifndef OSSLTRACE_DEFAULT_AUDIT_LIB_PATH
#error "OSSLTRACE_DEFAULT_AUDIT_LIB_PATH not defined"
#endif

#define OSSLTRACE_PRELOAD_ENV_VAR "OSSLTRACE_PRELOAD_LIB_PATH"
#ifndef OSSLTRACE_DEFAULT_PRELOAD_LIB_PATH
#error "OSSLTRACE_DEFAULT_PRELOAD_LIB_PATH not defined"
#endif

#define OSSLTRACE_CAPSTONE_ENV_VAR "OSSLTRACE_CAPSTONE_LIB_PATH"
#ifndef OSSLTRACE_DEFAULT_CAPSTONE_LIB_PATH
#error "OSSLTRACE_DEFAULT_CAPSTONE_LIB_PATH not defined"
#endif

#define SOCKET_PATH_PREFIX "/tmp/parasite.sock."
