#pragma once

#include "concat.h"

#define FUNC_POSTFIX 102930128401


#define _DECLARE_ORIGINAL_STORAGE(RET_TYPE, FUNC_NAME, ...) \
    volatile RET_TYPE (*CAT3(orig, FUNC_NAME, FUNC_POSTFIX))(__VA_ARGS__) = NULL;


#define GET_ORIGINAL(FUNC_NAME) \
    CAT3(orig, FUNC_NAME, FUNC_POSTFIX)


#define GET_ORIGINAL_NONTYPED(FUNC_NAME) \
    ((void *) GET_ORIGINAL(FUNC_NAME))


#define INVOKE_ORIGINAL(FUNC_NAME, ...) \
    GET_ORIGINAL(FUNC_NAME)(__VA_ARGS__)


#define SET_ORIGINAL(FUNC_NAME, PTR) \
    GET_ORIGINAL(FUNC_NAME) = PTR


#define DEF_PAYLOAD(RET_TYPE, FUNC_NAME, ...) \
    _DECLARE_ORIGINAL_STORAGE(RET_TYPE, FUNC_NAME, __VA_ARGS__) \
    RET_TYPE CAT3(payloaded, FUNC_NAME, FUNC_POSTFIX) (__VA_ARGS__)


#define GET_PAYLOAD(FUNC_NAME) \
    CAT3(payloaded, FUNC_NAME, FUNC_POSTFIX)


#define INVOKE_PAYLOAD(FUNC_NAME, ...) \
    GET_PAYLOAD(FUNC_NAME)(__VA_ARGS__)
