#pragma once

#define OSSLTRACE_LOG_OUTPUT_FILE_ENV_VAR "OSSLTRACE_LOG_OUTPUT_FILE"
#define OSSLTRACE_IGNORE_CA_ENV_VAR "OSSLTRACE_IGNORE_CA"
#define OSSLTRACE_SOCKET_PATH_ENV_VAR "OSSLTRACE_SOCKET_PATH"
