#pragma once

#define OSSLTRACE_LOG_OUTPUT_FILE_ENV_VAR "OSSLTRACE_LOG_OUTPUT_FILE"
#define OSSLTRACE_DENYLIST_FILE_ENV_VAR "OSSLTRACE_DENYLIST_FILE"
#define OSSLTRACE_IGNORE_CA_ENV_VAR "OSSLTRACE_IGNORE_CA_ENV_VAR"
