name: Build with makefile
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: install OpenSSL development headers and curl
      run: sudo apt update && sudo apt install -y libssl-dev curl
    
    - name: make build must return 0
      run: make build

    - name: build artifacts exist
      run: |
        test -d build/ && \
        test -f build/ossltrace && \
        test -f build/lib/libossl_audit.so && \
        test -f build/lib/libossl_preload.so

    - name: launcher can print help
      run: build/ossltrace -h

    - name: sudo make provides full installation
      run: sudo make

    - name: libs located at /usr/lib
      run: |
        test -f /usr/lib/libossl_audit.so && \
        test -f /usr/lib/libossl_preload.so

    - name: basic curl test with default preload mode 
      run: build/ossltrace -- curl -L --http1.1 -o/dev/null https://example.com
